data:extend({
    {
        type = "bool-setting",
        name = "battery-powered-dischargers",
        setting_type = "startup",
        default_value = true,
        order = "a1",
    },
    {
        type = "bool-setting",
        name = "battery-powered-decay",
        setting_type = "startup",
        default_value = true,
        order = "a2",
    },
    {
        type = "bool-setting",
        name = "battery-powered-delivery-cannon",
        setting_type = "startup",
        default_value = true,
        order = "a3",
    },
    {
        type = "bool-setting",
        name = "battery-powered-k2-fuel-rebalance",
        setting_type = "startup",
        default_value = true,
        order = "a4",
    },
    {
        type = "int-setting",
        name = "battery-powered-burnt-inventory-size",
        setting_type = "startup",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 5,
        -- allowed_values = { 1, 2, 3, 4, 5 },
        order = "a5",
    },
    {
        type = "bool-setting",
        name = "battery-powered-jetpack-fuel",
        setting_type = "startup",
        default_value = true,
        order = "a6",
    },
    {
        type = "bool-setting",
        name = "battery-powered-equipment-fuel",
        setting_type = "startup",
        default_value = true,
        order = "a7",
    },
})
